### ISSUE TITLE
Error  Cannot load configuration.

### ISSUE THREAD

**Issue by trebitzki** [aymericb/exposition#1]
Clean install of version 0.3 with grunt build. Build folder is installed locally on Mac 10.6.8 in ~/Sites/exposition. Put the absolute paths to photos and cache folders in config.php. The cache folder is world writable. Can't get past this error.

![screen shot 2013-08-08 at 21 10 44](https://f.cloud.github.com/assets/940634/933834/433eadb0-005e-11e3-97a6-6e08c084a8a7.png)

**Comment by trebitzki** [comment]
Issue solved. The line `RewriteBase /` in .htaccess must be set to the path from web root. In my case I set it to `RewriteBase /exposition`. ~~Works fine now, thanks.~~

**Comment by trebitzki** [comment]
That seems only part of the problem. Although the above error is gone and the album is shown, there are some more issues; I'll write them extra.

**Comment by aymericb** [comment]
Implicitly, I assumed that exposition is deployed in the root directory. I'll have to think of a good way to handle subdirectories.

**Comment by trebitzki** [comment]
Having a gallery as the homepage of a site seems sort of odd... Anyway I'm looking forward to a more flexible solution, thanks!

**Comment by aymericb** [comment]
I'll mark this as duplicate of Issue #2.
